### ISSUE TITLE
Support siren device type

### ISSUE THREAD

**Issue by BewhiskeredBard** [BewhiskeredBard/homebridge-scout#26]
…probably as a switch or a lightbulb. I have no idea if there's even a way to uniquely identify a siren accessory from the hub siren.

If you're interested in support, feel free to [sponsor me](https://github.com/sponsors/BewhiskeredBard) or [buy me one](https://www.scoutalarm.com/pages/accessories).

**Comment by jordanryanmoore** [comment]
If I add the `Switch` service directly to the same accessory, it shows up alongside, but I worry what Siri might do with "turn on security system". I need to do more testing.

**Comment by BewhiskeredBard** [comment]
Scout has de-listed the siren accessory from their website, after it was listed as "out of stock" for a very long time. I'm closing this issue. It can be re-opened if they re-launch the accessory in the future, or someone sends one to me.
